# Generated by Django 4.2 on 2025-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_dept_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Dept_Name',
            field=models.CharField(default='dept', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='Description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
